add workflow file5

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,12 +11,11 @@ jobs:
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-            - name: Failed Step
-              run: 
-                echo "I will fail"
-                exit 1
+            - name: Custom Error Step
+              run: |
+                echo "This step will fail"
+                exit 1  # 自定义错误
             - name: Say goodBye
-              if: success()  # 仅在前一步成功时执行
               run: echo "Good bye"
 
             
